### PR TITLE
Remove Google Guava dependency

### PR DESCRIPTION
**Pull request by sathishk**
We use Google Guava to dynamically discover our keyword implementations. Shall we use the plain java approach as described at https://dzone.com/articles/get-all-classes-within-package ?

### CODE REVIEW

**Comment by ssilverman** [comment]
Thank you for the pull request. I'm not going to merge this as-is because there are better ways to do this, but let me ask you this: do you have a need to remove the Guava dependency?

**Comment by sathishk** [comment]
Thanks, @ssilverman .

Agreed. There are better ways to do this. one is to calculate the Keywords at build time and avoid reflection entirely.

Removing additional jar dependencies will be helpful to reduce the overall size of the application. (For E.g in Spring Boot fatjar )

**Comment by ssilverman** [comment]
I'm going to change the dependency to use https://github.com/classgraph/classgraph for now because that should be smaller than Guava. The reason I started with reflection instead of hard-coding anything is to start the design so that it could support pluggable keywords for reflection.

**Comment by ssilverman** [comment]
In my experiments, changing to ClassGraph from Guava saves about 2.3 MiB.

**Comment by ssilverman** [comment]
I've updated the class scanning library to ClassGraph.

**Comment by ssilverman** [comment]
@sathishk Are you pointing these out because you have a specific need or just because you're trying to point out some inefficiencies?

**Comment by sathishk** [comment]
@ssilverman, not a specific need. 

in general, it is better to keep no dependencies down as this can increase the application artifact size

Also just to share my thoughts on JSON specific options, I see different libraries choose a different approach for various reasons 

For instance, 

1. implementations that use org.json which is a very low-level JSON API compared to  full-fledged libraries like Jackson or GSON ( E.g https://github.com/everit-org/json-schema )
2. implementations that use Jakarta JSON API to keep the code portable.  ( E.g https://github.com/leadpony/justify )

**Comment by ssilverman** [comment]
Yes, it's true that it's good to minimize dependencies, but I think it's appropriate here to use an external library to do class finding because it's a little involved. ClassGraph happens to be a little more advanced than Guava, which is why I switched to it, but it's possible Guava may appear again in the future for other uses.

Don't forget that if you really want to reduce application size, say in the Spring example you mention, you should use a tool that removes unused code. That will be the best thing if you truly need to minimize your application.

**Pull request closed without merging**
